"""Render measured examples from their checked-in provenance manifest."""
from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "static" / "examples"


def manifest() -> dict:
    return json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))


def download(name: str, label: str, data: dict) -> str:
    size = data["files"][name]["bytes"]
    return (f'<a href="/static/examples/{html.escape(name)}" data-ff-download download>'
            f'{html.escape(label)}</a> <span class="file-size">({size:,} bytes)</span>')


def render_example(kind: str) -> str:
    data = manifest()
    if kind == "compression":
        rows = "".join(
            f'<tr><th scope="row">{level.title()}</th><td>{m["compressed_size"]:,} bytes</td>'
            f'<td>{m["reduction_pct"]:.1f}%</td><td>{download(f"scan-{level}.pdf", "Download PDF", data)}</td></tr>'
            for level, m in data["compression"].items()
        )
        body = f'''<p>This one-page synthetic scan contains small text, thin rules and a color ramp.
            It has <strong>no selectable text</strong>. Compare each output with the original at 100% and 200% zoom.</p>
            <p>{download("scan.pdf", "Download the original scan", data)}</p>
            <p class="table-hint">Scroll the table sideways on small screens to compare all columns.</p>
            <div class="table-scroll" role="region" aria-label="Compression example results" tabindex="0"><table>
            <caption>Actual output from this fixture; savings on your files will differ.</caption>
            <thead><tr><th scope="col">Level</th><th scope="col">Output size</th><th scope="col">Reduction</th><th scope="col">Result</th></tr></thead>
            <tbody>{rows}</tbody></table></div>
            <div class="example-figures"><figure><img src="/static/examples/scan-before.png" width="714" height="1011" loading="lazy" alt="Original synthetic scanned worksheet with small text and fine rules"><figcaption>Original scan</figcaption></figure>
            <figure><img src="/static/examples/scan-after.png" width="714" height="1011" loading="lazy" alt="Same worksheet after high PDF compression"><figcaption>High compression. Download to inspect small print at full size.</figcaption></figure></div>'''
    elif kind == "word":
        body = f'''<p>A three-page workshop report with selectable text, headings, a materials table and fine print.
            The DOCX below was produced by the standard converter. Inspect table cells, page breaks and line wrapping;
            this simple fixture does not demonstrate accuracy on scans or complex layouts.</p>
            <p>{download("report.pdf", "Original PDF", data)}<br>{download("report.docx", "Actual converted Word document", data)}</p>
            <figure class="example-preview"><img src="/static/examples/report-preview.png" width="714" height="1011" loading="lazy" alt="First page of the original workshop report with heading and materials table"><figcaption>The original PDF. Open the DOCX in your editor to check editability.</figcaption></figure>'''
    elif kind == "heic":
        body = f'''<p>A generated 1200 × 800 color-and-edge test image, encoded as HEIC and converted with JPEG quality 95.
            Both formats are lossy. This is a compatibility example, not an iPhone camera, HDR, or Live Photo test.</p>
            <p>{download("pattern.heic", "Original HEIC", data)}<br>{download("pattern.jpg", "Converted JPG", data)}</p>
            <figure><img src="/static/examples/pattern.jpg" width="1200" height="800" loading="lazy" alt="Converted diagnostic image with a color gradient and rectangular swatches"><figcaption>Actual JPEG output; 1200 × 800 pixels.</figcaption></figure>'''
    elif kind == "pages":
        body = f'''<p>The report contains three numbered pages. Merging it with the one-page appendix produces four pages;
            extracting <code>1,3</code> from the report produces two. The downloadable outputs below were generated by these tools.</p>
            <ul><li>{download("report.pdf", "Three-page report", data)}</li><li>{download("appendix.pdf", "One-page appendix", data)}</li>
            <li>{download("merged.pdf", "Merged four-page PDF", data)}</li><li>{download("extracted.pdf", "Extracted pages 1 and 3", data)}</li></ul>'''
    else:
        raise ValueError(f"Unknown example: {kind}")
    return f'''<section class="worked-example" aria-label="Worked example">
        <p class="eyebrow">TRY IT WITH A PRACTICE FILE</p><h2>A reproducible example</h2>{body}
        <details><summary>How this example was made</summary><p>{html.escape(data["provenance"])}
        {html.escape(data["method"])}</p><p>Generated and checked on <time datetime="{data["reviewed"]}">{data["reviewed"]}</time>.
        <a href="/static/examples/manifest.json" data-ff-download download>Exact sizes, hashes and software versions</a> ·
        <a href="https://github.com/BhurkeSiddhesh/Forge-Files/blob/main/scripts/build_content_examples.py">Reproduction script</a>.</p></details></section>'''
